server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wangfang.springcloud.entites
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    admin: microservice-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.145.128:3306/cloudDB01
    username: root
    password: "@Wangfang123"
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

