server:
  port: 7003
eureka:
  server:
    enable-self-preservation: true  # false 关闭自我保护机制
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护实例，不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #设置于eureka Server交互地址查询服务和注册地址
